# Register at https://openweathermap.org to get your API key
api_key = "ad12ce9f4193487f7bc3b511d632b0f8"

# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "5809844"

# Display settings
units = "imperial"
display_symbol = "°F"
